# Generated by Django 6.0 on 2025-12-17 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, help_text='When the book was checked out')),
                ('due_date', models.DateTimeField(help_text='When the book should be returned')),
                ('returned_at', models.DateTimeField(blank=True, help_text='When the book was checked in (null if still borrowed)', null=True)),
                ('book', models.ForeignKey(help_text='Book that was borrowed', on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book')),
                ('user', models.ForeignKey(help_text='User who borrowed the book', on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrowing',
                'verbose_name_plural': 'Borrowings',
                'db_table': 'borrowings',
                'ordering': ['-borrowed_at'],
                'indexes': [models.Index(fields=['user', 'returned_at'], name='borrowings_user_id_c98eeb_idx'), models.Index(fields=['book', 'returned_at'], name='borrowings_book_id_c60dc0_idx')],
            },
        ),
    ]
